### ISSUE TITLE
`eatlocal download 27` not working

### ISSUE THREAD

**Issue by Zaubeerer** [PyBites-Open-Source/eatlocal#31]
While on my mac `eatlocal download` works fine, on my windows machine I get the following error:

![image](https://user-images.githubusercontent.com/60844432/180605727-72429083-1608-4422-941e-430a30d2c3db.png)

**Comment by rhelmstedter** [comment]
Hi, glad it works on your mac.

Which terminal are you using on windows? e.g., WSL, Powershell? `eatlocal` does not work with [WSL2](https://github.com/PyBites-Open-Source/eatlocal#wsl) but should work on windows otherwise.

Given that your credentials work on your mac and the error is related to downloading, it is probably a network/chromedriver problem. Can you confirm that your version of chromedriver matches your version of chrome on your windows machine?

**Comment by Zaubeerer** [comment]
I updated both via `choco upgrade chromedrive` and `choco upgrade googlechrome` to the latest version `106.0.5249.119`.

However, I still get the following error:
```sh
(biteme) PS C:\Users\rbeer> eatlocal download 1
⠏ Downloading Bite 1
DevTools listening on ws://127.0.0.1:50358/devtools/browser/1e18c6f0-cd5c-4f7d-9114-2d2455f3cd2d
⚠ Bite 1 was not downloaded. Ensure you are connected to the internet 
and your PyBites credentials are valid.
⚠ Missing ZIP archive for bite 1: pybites_bite1.zip
```

**Comment by Zaubeerer** [comment]
Just checked the eatlocal config file and it turned out that the password was not set properly.

Probably a terminal related copy paste error 🤔 

Adding the pybitees password manually solved the problem!
