### ISSUE TITLE
Error upon downloading premium (inaccessible) Bite

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/eatlocal#40]
```
AttributeError: 'NoneType' object has no attribute 'text'
```

Which is good (no data leak), but the bite should not be listed with `display` = fix.

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/b9140c6e-7a98-4f2f-bae2-c8e3d9428a37">

<img width="528" alt="image" src="https://github.com/user-attachments/assets/29311efc-69ce-4e77-a5ca-e6b319daa37c">

Thanks,
Bob

**Comment by bbelderbos** [comment]
Maybe discard rows with lock icon in `choose_bite`?

```
    for row in rows[1:]:
        try:
            bite = row.find_all("td")[1].a
            bite_name = bite.text
            bite_link = bite["href"]
            bites[bite_name] = bite_link
        except IndexError:
            continue

```

I noted `EXERCISES_URL = "https://pybitesplatform.com/bites/regular/"` so this won't work for newbies and intros?

Also typo here: `with Status("Retrievng bites...")`

**Comment by rhelmstedter** [comment]
Got it. I only check if the user can't log in. I forgot about users who can log it, but don't have premium access. I'll work on that in a new branch.

v1 didn't work for newbies. I think it shouldn't be too difficult to add. Should be just navigating to the newbie and intro tables and adding them to the dictionary. 

@olgamirth do either of these issues interest you?

**Comment by rhelmstedter** [comment]
>Maybe discard rows with lock icon in choose_bite?

Ok, doing some more digging, we'll have to change more than I thought. Currently I am retrieving the table of bites without logging in because that made it faster. But if you look at the table of bites without being logged in there is no status column, so I can't tell which are premium.

We can login first to retrieve the bites. It'll just go slower each time you try to download.

Is there a way to cache the exercises list? I have two thoughts:

1. Originally, I had thought about building the bites dict directly into `eatlocal`, but then we would have to update `eatlocal` each time a new bite is published. That sounds terrible :).
2. What if during `eatlocal init` we fetch all the bites the user has access to and save it within the `.eatlocal` directory in a json file. Basically just a dictionary `{<bite name>: <bite url>, ...}`. Then create a new command, `eatlocal updatebites`. When that is run, it fetches all the available exercises again. This would keep or even increase the speed of retrieving the bites each time. If a user stops paying for premium, they can run `eatlocal updatebites` and it will remove all the premium bites as options to download. If a non premium user upgrades and they run `eatlocal updatebites` it'll pull in all the premium bites.

**Comment by bbelderbos** [comment]
Logged newbies/intros here: https://github.com/PyBites-Open-Source/eatlocal/issues/43

**Comment by bbelderbos** [comment]
Thanks for the username = email issue.

**Comment by bbelderbos** [comment]
@rhelmstedter fastest for us would be for me to just provide a new exercises endpoint, similar how we have in v1? https://codechalleng.es/api/bites

Then you can just fetch that.

Problem is we show bites people might not have access to, but can we then just catch that when they attempt to download it? That's a similar experience for somebody going to the premium bite page as free user and finding a "start free trial" button (and code editor hidden).

**Comment by rhelmstedter** [comment]
If you're willing to create that api that lists all the bites (including newbies and intros), that is way easier. Then we would just catch the `AttributeError` for the bites where people don't have access.

**Comment by bbelderbos** [comment]
Yes easy, will do on Monday, but that's all bites (just meta data, not authenticated), right?
And then we show all (maybe add newbie|intro|regular column), and only error out when we find out that when selecting a Bite they don't have access to (here the login has happened), ok?

**Comment by bbelderbos** [comment]
Yep I will add that api asap ...

**Comment by bbelderbos** [comment]
related: https://github.com/PyBites-Open-Source/eatlocal/issues/43

**Comment by bbelderbos** [comment]
And you! haha

Happy to hear, it's also exposed in the UI now:

<img width="862" alt="image" src="https://github.com/user-attachments/assets/69350e24-10b8-4c88-afed-52108aa9932e">

**Comment by rhelmstedter** [comment]
I don't have the bandwidth to actually code this tonight, but doing some thinking.

I'm looking at your new api (which is amazing), and thinking we should just use the slug for the directory name. Currently, I'm replacing the `-` -> `_` because I'm used to naming python stuff with underscores. But that just seems like an extra step / point for things to go wrong. What do you think?

**Comment by bbelderbos** [comment]
Seems a matter of taste? I'm happy to use the slug. Need help? Maybe I can give this a shot?

**Comment by rhelmstedter** [comment]
[0aa53de](https://github.com/PyBites-Open-Source/eatlocal/pull/44/commits/0aa53de2682e86859fe5e08292f103e2bf9e722c) addresses the original issue. 

Tests are passing except for one because I need to mock out the request.get.json() but I'm not sure how yet.

**Comment by rhelmstedter** [comment]
> <img alt="image" width="1165" src="https://private-user-images.githubusercontent.com/387927/384355592-b9140c6e-7a98-4f2f-bae2-c8e3d9428a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTk4NDAsIm5iZiI6MTczMTU1OTU0MCwicGF0aCI6Ii8zODc5MjcvMzg0MzU1NTkyLWI5MTQwYzZlLTdhOTgtNGYyZi1iYWUyLWM4ZTNkOTQyOGEzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNDQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTcxZGMxZjQ2OWQ1NTFlN2UxYTNhYzdkZDU4NDdhYWY1YWExOTEyYjYyNjlhMDdhZjExNWI1NGIxNmY3Y2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jjxq2QS04XmNcSFyABIydCDr3aLAXA4qaGAzkFDXRyU"> <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/387927/384355652-29311efc-69ce-4e77-a5ca-e6b319daa37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTk4NDAsIm5iZiI6MTczMTU1OTU0MCwicGF0aCI6Ii8zODc5MjcvMzg0MzU1NjUyLTI5MzExZWZjLTY5Y2UtNGU3Ny1hNWNhLWU2YjMxOWRhYTM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNDQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2FhYzhjNDlkY2NjMTIyOWExM2Q4ZDIxZjQ1ZjlmNmI5YzZlZDBmZDk4ZDJmYmU5NTJiMmYzYTE4Yjg0ZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jEFEseDIpTyXg0p0ePiX7E0iUpn2_HXVsOjmfFn3n1g">

Added bonus, I fixed this rendering issue. The rich Status was interfering with the iterfzf interface.

**Comment by bbelderbos** [comment]
Thanks, lol talking rendering the images above don't render for me, but I can try.

**Comment by rhelmstedter** [comment]
hahaha sorry. I swear it worked when I posted it. But the images are not rendering for me either.
